// agent/core/agent-loop.js

// Import necessary modules from other parts of the agent.
const { generateResponse } = require('./llm-client');

/**
 * Executes a single cycle of the agent's operation.
 * 
 * @param {string} userInput - The text input provided by the user.
 * @returns {Promise<string>} The text response generated by the LLM for the user.
 * @throws {Error} If any step in the cycle fails.
 */
async function runAgentCycle(userInput) {
  // Basic validation for user input.
  if (!userInput || typeof userInput.trim() !== 'string' || userInput.trim() === '') {
    throw new Error("Invalid user input provided for agent cycle. Input cannot be empty.");
  }

  try {
    // 1. Generate the main response from the LLM to show to the user.
    console.log(`Agent loop: Requesting LLM response for: "${userInput}"`);
    const llmResponse = await generateResponse(userInput);
    console.log(`Agent loop: Received response from LLM.`);

    // 2. Return the primary LLM response to be displayed in the UI.
    return llmResponse;

  } catch (error) {
    console.error(`Agent Cycle Error: ${error.message}`);
    // Re-throw the error so it can be caught and handled by the entry point (e.g., index.js).
    throw error;
  }
}

// Export the updated runAgentCycle function.
module.exports = {
  runAgentCycle,
};
