const { GoogleGenAI } = require("@google/genai"); 
const path = require('path');
// Explicitly load .env from project root
require("dotenv").config({ path: path.join(__dirname, '../../.env') }); 

const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
const MODEL_NAME = "models/gemini-flash-latest"; // As specified in the user's goal

let genAI;
// We'll use a flag to track if the client was successfully initialized
let isClientInitialized = false; 

// Initialize the Gemini client once when the module is loaded.
if (!GEMINI_API_KEY) {
  console.error("❌ ERROR: GEMINI_API_KEY is missing. Please ensure it is set correctly in your project's root .env file and that the path in llm-client.js is correct.");
  // If API key is missing, initialization is considered failed.
} else {
  try {
    // Use the original instantiation pattern: new GoogleGenAI({ apiKey })
    genAI = new GoogleGenAI({ apiKey: GEMINI_API_KEY }); 
    // We don't get a separate 'model' object here; the original code called genAI.models.generateContent
    isClientInitialized = true; // Mark as initialized if constructor succeeded and key was present
  } catch (error) {
    // Catch errors during the GoogleGenAI instantiation itself.
    console.error("❌ Error initializing Gemini client:", error.message);
    // isClientInitialized remains false.
  }
}

/**
 * Generates a text response from the Gemini API using the original method structure.
 * * @param {string} prompt - The user's input prompt.
 * @returns {Promise<string>} The text content generated by the LLM.
 * @throws {Error} If the client is not initialized or LLM call errors.
 */
async function generateResponse(prompt) {
  // Check if the client was successfully initialized
  if (!isClientInitialized || !genAI) {
    // This error message is now more accurate, covering both missing key and initialization failures.
    throw new Error("LLM client is not initialized. Please ensure GEMINI_API_KEY is set correctly and the Gemini library is functioning.");
  }

  try {
    // Use the original calling pattern: genAI.models.generateContent
    const result = await genAI.models.generateContent({ 
        model: MODEL_NAME, // Use the constant for model name
        contents: [{ text: prompt }] 
    });

    // Extract text from the result, mirroring original logic with safety checks
    if (result && result.candidates && result.candidates.length > 0 && 
        result.candidates[0].content && result.candidates[0].content.parts && 
        result.candidates[0].content.parts.length > 0) {
        
        const responseText = result.candidates[0].content.parts[0].text;
        return responseText;
    } else {
        // Log unexpected response structure for debugging
        console.error("LLM returned an unexpected response structure:", JSON.stringify(result, null, 2));
        throw new Error("Failed to extract valid text from LLM response.");
    }
    
  } catch (error) {
    console.error("❌ Error during LLM generation:", error.message);
    // Re-throw the error so it can be caught and handled by the agent loop
    throw error;
  }
}

// Export the function to be used by other modules
module.exports = {
  generateResponse,
};